server:
  port: 10001
spring:
  profiles:
  application:
    name: itaza-order
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 685706
    hikari:
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 30
      pool-name: HikariConnectionPool
  redis:
    database: 10
    host: visva-sit.redis.rds.aliyuncs.com
    port: 6379
    password: WmaiVisva2018
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 2ms
    timeout: 5000ms

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    # 允许将表中null值字段映射到对象字段中
    call-setters-on-nulls: true
